import { docs } from "@/.source/server"
import { loader } from "fumadocs-core/source"

// The docs page tree + page lookup, served under /docs.
// `docs` is generated by fumadocs-mdx into `.source` from content/docs.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
})
