import coreWebVitals from "eslint-config-next/core-web-vitals"
import nextTypescript from "eslint-config-next/typescript"

/** Flat config — ESLint 9 dropped .eslintrc, and `next lint` is gone in Next 16,
 *  so `npm run lint` calls eslint directly.
 *
 *  eslint-config-next 16 ships flat config arrays, so no FlatCompat shim is
 *  needed. `core-web-vitals` is the stricter of the two Next presets: it
 *  promotes the image/script/font rules from warn to error, which is what you
 *  want in a repo where nobody is watching warnings.
 */
export default [
  {
    ignores: [
      ".next/**",
      "out/**",
      "next-env.d.ts",
      // Generated by the domscribe bundler plugin, not ours to lint.
      ".domscribe/**",
      // Generated by fumadocs-mdx at build time.
      ".source/**",
    ],
  },
  ...coreWebVitals,
  ...nextTypescript,
  {
    name: "xcomm-hud/overrides",
    rules: {
      // The codebase uses `_`-prefixed names for deliberately unused bindings
      // (destructured-and-discarded props, catch params). Without this the
      // convention reads as a lint failure rather than the signal it is.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],

      // ---- Known backlog, warn not error ----
      // These two arrived with react-hooks v6 and fire across code written
      // long before the rules existed. They are NOT disabled: they still print
      // on every run, so the backlog stays visible and new instances are
      // obvious in a diff. They are warnings so that `npm run lint` can be a
      // meaningful gate today rather than failing on 57 pre-existing hits.
      //
      // set-state-in-effect (36): mostly the sync-props-into-state pattern.
      // Each needs judging on its own — some genuinely want deriving instead,
      // others are legitimate external-store syncs. Not a mechanical fix.
      //
      // static-components (21): a real anti-pattern in places (components
      // closed over parent state, e.g. <SortHeader> in gateways-admin, which
      // remount every render) and a false positive in others (`const Icon =
      // equipmentIcon(...)` returns a stable module-level reference). Fixing
      // means hoisting the real ones out, which is a refactor, not a setting.
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/static-components": "warn",
    },
  },
]
